// <auto-generated />
using System;
using Infra.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20201121141249_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Escolaridade", b =>
                {
                    b.Property<int>("CodEscolaridade");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50);

                    b.HasKey("CodEscolaridade");

                    b.ToTable("Escolaridade");

                    b.HasData(
                        new { CodEscolaridade = 1, Nivel = "Infantil" },
                        new { CodEscolaridade = 2, Nivel = "Fundamental" },
                        new { CodEscolaridade = 3, Nivel = "Médio" },
                        new { CodEscolaridade = 4, Nivel = "Superior" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodEscolaridade");

                    b.Property<DateTime?>("DtNascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .HasMaxLength(90);

                    b.Property<string>("SobreNome")
                        .HasMaxLength(200);

                    b.HasKey("IdUsuario");

                    b.HasIndex("CodEscolaridade");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Usuarios", b =>
                {
                    b.HasOne("Domain.Entities.Escolaridade", "Escolaridade")
                        .WithMany("usuarios")
                        .HasForeignKey("CodEscolaridade")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
